name: biruu_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  google_fonts: ^6.2.1
  flutter_vector_icons: ^2.0.0
  table_calendar: ^3.0.9
  intl: ^0.20.2
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1
  flutter_native_timezone: ^2.0.0
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  firebase_auth: ^5.6.0
  firebase_auth_web: ^5.8.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
